In [2]:
import pandas as pd

In [193]:
df = pd.read_csv('/Users/nancybaraka/Desktop/IronHack/Week 2/FAOSTAT_data_en_9-24-2024.csv')

In [195]:
df.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,QCL,Crops and livestock products,356,India,5312,Area harvested,01654,"Anise, badian, coriander, cumin, caraway, fenn...",1961,1961,ha,90000.0,E,Estimated value,NaN
1,QCL,Crops and livestock products,356,India,5419,Yield,01654,"Anise, badian, coriander, cumin, caraway, fenn...",1961,1961,100 g/ha,5000.0,E,Estimated value,NaN
2,QCL,Crops and livestock products,356,India,5510,Production,01654,"Anise, badian, coriander, cumin, caraway, fenn...",1961,1961,t,45000.0,E,Estimated value,NaN
3,QCL,Crops and livestock products,356,India,5312,Area harvested,01654,"Anise, badian, coriander, cumin, caraway, fenn...",1962,1962,ha,90000.0,E,Estimated value,NaN
4,QCL,Crops and livestock products,356,India,5419,Yield,01654,"Anise, badian, coriander, cumin, caraway, fenn...",1962,1962,100 g/ha,5000.0,E,Estimated value,NaN

In [197]:
fao_india_data = df[df['Area'] == 'India']

In [199]:
fao_india_data.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,QCL,Crops and livestock products,356,India,5312,Area harvested,01654,"Anise, badian, coriander, cumin, caraway, fenn...",1961,1961,ha,90000.0,E,Estimated value,NaN
1,QCL,Crops and livestock products,356,India,5419,Yield,01654,"Anise, badian, coriander, cumin, caraway, fenn...",1961,1961,100 g/ha,5000.0,E,Estimated value,NaN
2,QCL,Crops and livestock products,356,India,5510,Production,01654,"Anise, badian, coriander, cumin, caraway, fenn...",1961,1961,t,45000.0,E,Estimated value,NaN
3,QCL,Crops and livestock products,356,India,5312,Area harvested,01654,"Anise, badian, coriander, cumin, caraway, fenn...",1962,1962,ha,90000.0,E,Estimated value,NaN
4,QCL,Crops and livestock products,356,India,5419,Yield,01654,"Anise, badian, coriander, cumin, caraway, fenn...",1962,1962,100 g/ha,5000.0,E,Estimated value,NaN

In [170]:
token = "N5M3PUXR525TXA52UVXE4766F"

In [201]:
import requests
import numpy as np

# Define cities and coordinates for weather data in India
cities = {
    'New Delhi': '28.6139,77.2090',
    'Mumbai': '19.0760,72.8777',
    'Kolkata': '22.5726,88.3639',
    'Chennai': '13.0827,80.2707',
    'Bangalore': '12.9716,77.5946'
}

# Define the Visual Crossing API key
api_key = "N5M3PUXR525TXA52UVXE4766F"

# Define the date range (adjust as needed)
start_date = "2022-01-01"
end_date = "2022-01-07"

# Initialize lists to store temperature and humidity data
temperature_data = []
humidity_data = []

# Fetch weather data for each city
for city, coordinates in cities.items():
    # Construct the API URL
    url = f"https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/{coordinates}/{start_date}/{end_date}?unitGroup=metric&key={api_key}&include=obs"
    
    # Fetch the weather data
    response = requests.get(url)
    
    if response.status_code == 200:
        weather_data = response.json()
        
        # Extract temperature and humidity from the "days" section
        for day in weather_data['days']:
            temperature_data.append(day['temp'])
            humidity_data.append(day['humidity'])
    else:
        print(f"Failed to fetch data for {city}, status code: {response.status_code}")

# Calculate the average temperature and humidity across all cities
average_temperature = np.mean(temperature_data)
average_humidity = np.mean(humidity_data)

average_temperature, average_humidity

(21.30857142857143, 77.20857142857143)

In [203]:
# Add the averaged weather data (temperature and humidity) to the FAO India dataset
fao_india_data['Average_Temperature'] = average_temperature
fao_india_data['Average_Humidity'] = average_humidity

# Display the updated FAO India dataset with the new weather columns
fao_india_data.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note,Average_Temperature,Average_Humidity
0,QCL,Crops and livestock products,356,India,5312,Area harvested,01654,"Anise, badian, coriander, cumin, caraway, fenn...",1961,1961,ha,90000.0,E,Estimated value,NaN,21.308571,77.208571
1,QCL,Crops and livestock products,356,India,5419,Yield,01654,"Anise, badian, coriander, cumin, caraway, fenn...",1961,1961,100 g/ha,5000.0,E,Estimated value,NaN,21.308571,77.208571
2,QCL,Crops and livestock products,356,India,5510,Production,01654,"Anise, badian, coriander, cumin, caraway, fenn...",1961,1961,t,45000.0,E,Estimated value,NaN,21.308571,77.208571
3,QCL,Crops and livestock products,356,India,5312,Area harvested,01654,"Anise, badian, coriander, cumin, caraway, fenn...",1962,1962,ha,90000.0,E,Estimated value,NaN,21.308571,77.208571
4,QCL,Crops and livestock products,356,India,5419,Yield,01654,"Anise, badian, coriander, cumin, caraway, fenn...",1962,1962,100 g/ha,5000.0,E,Estimated value,NaN,21.308571,77.208571

In [172]:
import requests
location = "Mumbai"
start_date = "2022-01-01"
end_date = "2022-01-07"

In [174]:
url = "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/Mumbai/2022-01-01/2022-01-07?unitGroup=metric&key=N5M3PUXR525TXA52UVXE4766F&include=obs"

In [176]:

response = requests.get(url)

In [178]:
print(response.headers.get('Content-Type'))

application/json

In [152]:
print(response.text)

{"queryCost":7,"latitude":18.9402,"longitude":72.8348,"resolvedAddress":"Mumbai, MH, India","address":"Mumbai","timezone":"Asia/Kolkata","tzoffset":5.5,"days":[{"datetime":"2022-01-01","datetimeEpoch":1640975400,"tempmax":31.4,"tempmin":22.7,"temp":26.6,"feelslikemax":32.2,"feelslikemin":22.7,"feelslike":27.0,"dew":17.7,"humidity":59.0,"precip":0.0,"precipprob":0.0,"precipcover":0.0,"preciptype":null,"snow":null,"snowdepth":null,"windgust":null,"windspeed":14.8,"winddir":24.6,"pressure":1015.7,"cloudcover":25.8,"visibility":2.9,"solarradiation":null,"solarenergy":null,"uvindex":null,"sunrise":"07:11:49","sunriseEpoch":1641001309,"sunset":"18:12:33","sunsetEpoch":1641040953,"moonphase":0.95,"conditions":"Partially cloudy","description":"Partly cloudy throughout the day.","icon":"partly-cloudy-day","stations":["VABB","VAJJ","43003099999","43057099999","43060099999"],"source":"obs"},{"datetime":"2022-01-02","datetimeEpoch":1641061800,"tempmax":31.1,"tempmin":22.7,"temp":27.0,"feelslikemax":32.8,"feelslikemin":22.7,"feelslike":27.7,"dew":18.8,"humidity":61.7,"precip":0.0,"precipprob":0.0,"precipcover":0.0,"preciptype":null,"snow":null,"snowdepth":null,"windgust":null,"windspeed":17.2,"winddir":6.8,"pressure":1014.1,"cloudcover":19.7,"visibility":2.6,"solarradiation":null,"solarenergy":null,"uvindex":null,"sunrise":"07:12:09","sunriseEpoch":1641087729,"sunset":"18:13:10","sunsetEpoch":1641127390,"moonphase":0.98,"conditions":"Clear","description":"Clear conditions throughout the day.","icon":"clear-day","stations":["VABB","VAJJ","43003099999","43057099999","43060099999"],"source":"obs"},{"datetime":"2022-01-03","datetimeEpoch":1641148200,"tempmax":31.7,"tempmin":23.3,"temp":27.2,"feelslikemax":32.9,"feelslikemin":23.3,"feelslike":27.9,"dew":18.9,"humidity":61.9,"precip":0.0,"precipprob":0.0,"precipcover":0.0,"preciptype":null,"snow":null,"snowdepth":null,"windgust":null,"windspeed":16.7,"winddir":298.5,"pressure":1013.7,"cloudcover":23.0,"visibility":2.8,"solarradiation":null,"solarenergy":null,"uvindex":null,"sunrise":"07:12:28","sunriseEpoch":1641174148,"sunset":"18:13:47","sunsetEpoch":1641213827,"moonphase":0.0,"conditions":"Partially cloudy","description":"Partly cloudy throughout the day.","icon":"partly-cloudy-day","stations":["43058099999","VABB","VAJJ","43003099999","43057099999","43060099999"],"source":"obs"},{"datetime":"2022-01-04","datetimeEpoch":1641234600,"tempmax":31.0,"tempmin":23.3,"temp":27.1,"feelslikemax":32.8,"feelslikemin":23.3,"feelslike":27.9,"dew":19.4,"humidity":63.5,"precip":0.0,"precipprob":0.0,"precipcover":0.0,"preciptype":null,"snow":null,"snowdepth":null,"windgust":null,"windspeed":15.4,"winddir":224.0,"pressure":1013.7,"cloudcover":0.6,"visibility":2.6,"solarradiation":null,"solarenergy":null,"uvindex":null,"sunrise":"07:12:45","sunriseEpoch":1641260565,"sunset":"18:14:24","sunsetEpoch":1641300264,"moonphase":0.05,"conditions":"Clear","description":"Clear conditions throughout the day.","icon":"clear-day","stations":["43058099999","VABB","VAJJ","43003099999","43057099999","43060099999"],"source":"obs"},{"datetime":"2022-01-05","datetimeEpoch":1641321000,"tempmax":30.4,"tempmin":23.4,"temp":26.5,"feelslikemax":32.0,"feelslikemin":23.4,"feelslike":27.4,"dew":21.0,"humidity":72.9,"precip":0.0,"precipprob":0.0,"precipcover":0.0,"preciptype":null,"snow":null,"snowdepth":null,"windgust":null,"windspeed":14.9,"winddir":281.7,"pressure":1013.2,"cloudcover":1.1,"visibility":2.1,"solarradiation":null,"solarenergy":null,"uvindex":null,"sunrise":"07:13:02","sunriseEpoch":1641346982,"sunset":"18:15:02","sunsetEpoch":1641386702,"moonphase":0.08,"conditions":"Clear","description":"Clear conditions throughout the day.","icon":"clear-day","stations":["43058099999","VABB","VAJJ","43003099999","43057099999","43060099999"],"source":"obs"},{"datetime":"2022-01-06","datetimeEpoch":1641407400,"tempmax":28.7,"tempmin":23.2,"temp":25.7,"feelslikemax":30.1,"feelslikemin":23.2,"feelslike":26.2,"dew":20.5,"humidity":74.0,"precip":0.0,"precipprob":0.0,"precipcover":0.0,"preciptype":null,"snow":null,"snowdepth":null,"windgust":null,"windspeed":18.7,"winddir":313.5,"pressure":1012.8,"cloudcover":11.2,"visibility":2.5,"solarradiation":null,"solarenergy":null,"uvindex":null,"sunrise":"07:13:18","sunriseEpoch":1641433398,"sunset":"18:15:40","sunsetEpoch":1641473140,"moonphase":0.11,"conditions":"Clear","description":"Clear conditions throughout the day.","icon":"clear-day","stations":["43058099999","VABB","VAJJ","43003099999","43057099999","43060099999"],"source":"obs"},{"datetime":"2022-01-07","datetimeEpoch":1641493800,"tempmax":28.8,"tempmin":22.2,"temp":25.6,"feelslikemax":31.0,"feelslikemin":22.2,"feelslike":26.3,"dew":20.6,"humidity":74.8,"precip":0.0,"precipprob":0.0,"precipcover":0.0,"preciptype":null,"snow":null,"snowdepth":null,"windgust":null,"windspeed":18.7,"winddir":205.3,"pressure":1012.2,"cloudcover":5.2,"visibility":2.3,"solarradiation":null,"solarenergy":null,"uvindex":null,"sunrise":"07:13:32","sunriseEpoch":1641519812,"sunset":"18:16:18","sunsetEpoch":1641559578,"moonphase":0.15,"conditions":"Clear","description":"Clear conditions throughout the day.","icon":"clear-day","stations":["43058099999","VABB","VAJJ","43003099999","43057099999","43060099999"],"source":"obs"}],"stations":{"43058099999":{"distance":34329.0,"latitude":18.633,"longitude":72.867,"useCount":0,"id":"43058099999","name":"ALIBAG, IN","quality":53,"contribution":0.0},"43003099999":{"distance":16894.0,"latitude":19.089,"longitude":72.868,"useCount":0,"id":"43003099999","name":"CHHATRAPATI SHIVAJI INTERNATIONAL, IN","quality":99,"contribution":0.0},"43057099999":{"distance":4864.0,"latitude":18.9,"longitude":72.817,"useCount":0,"id":"43057099999","name":"BOMBAY COLABA, IN","quality":55,"contribution":0.0},"VABB":{"distance":20023.0,"latitude":19.12,"longitude":72.84,"useCount":0,"id":"VABB","name":"VABB","quality":50,"contribution":0.0},"VAJJ":{"distance":19081.0,"latitude":19.11,"longitude":72.81,"useCount":0,"id":"VAJJ","name":"VAJJ","quality":21,"contribution":0.0},"43060099999":{"distance":47461.0,"latitude":18.983,"longitude":73.283,"useCount":0,"id":"43060099999","name":"MATHERAN, IN","quality":54,"contribution":0.0}}}

In [180]:
weather_data = response.json()

In [182]:
weather_data

{'queryCost': 7,
 'latitude': 18.9402,
 'longitude': 72.8348,
 'resolvedAddress': 'Mumbai, MH, India',
 'address': 'Mumbai',
 'timezone': 'Asia/Kolkata',
 'tzoffset': 5.5,
 'days': [{'datetime': '2022-01-01',
   'datetimeEpoch': 1640975400,
   'tempmax': 31.4,
   'tempmin': 22.7,
   'temp': 26.6,
   'feelslikemax': 32.2,
   'feelslikemin': 22.7,
   'feelslike': 27.0,
   'dew': 17.7,
   'humidity': 59.0,
   'precip': 0.0,
   'precipprob': 0.0,
   'precipcover': 0.0,
   'preciptype': None,
   'snow': None,
   'snowdepth': None,
   'windgust': None,
   'windspeed': 14.8,
   'winddir': 24.6,
   'pressure': 1015.7,
   'cloudcover': 25.8,
   'visibility': 2.9,
   'solarradiation': None,
   'solarenergy': None,
   'uvindex': None,
   'sunrise': '07:11:49',
   'sunriseEpoch': 1641001309,
   'sunset': '18:12:33',
   'sunsetEpoch': 1641040953,
   'moonphase': 0.95,
   'conditions': 'Partially cloudy',
   'description': 'Partly cloudy throughout the day.',
   'icon': 'partly-cloudy-day',
   'stations': ['VABB', 'VAJJ', '43003099999', '43057099999', '43060099999'],
   'source': 'obs'},
  {'datetime': '2022-01-02',
   'datetimeEpoch': 1641061800,
   'tempmax': 31.1,
   'tempmin': 22.7,
   'temp': 27.0,
   'feelslikemax': 32.8,
   'feelslikemin': 22.7,
   'feelslike': 27.7,
   'dew': 18.8,
   'humidity': 61.7,
   'precip': 0.0,
   'precipprob': 0.0,
   'precipcover': 0.0,
   'preciptype': None,
   'snow': None,
   'snowdepth': None,
   'windgust': None,
   'windspeed': 17.2,
   'winddir': 6.8,
   'pressure': 1014.1,
   'cloudcover': 19.7,
   'visibility': 2.6,
   'solarradiation': None,
   'solarenergy': None,
   'uvindex': None,
   'sunrise': '07:12:09',
   'sunriseEpoch': 1641087729,
   'sunset': '18:13:10',
   'sunsetEpoch': 1641127390,
   'moonphase': 0.98,
   'conditions': 'Clear',
   'description': 'Clear conditions throughout the day.',
   'icon': 'clear-day',
   'stations': ['VABB', 'VAJJ', '43003099999', '43057099999', '43060099999'],
   'source': 'obs'},
  {'datetime': '2022-01-03',
   'datetimeEpoch': 1641148200,
   'tempmax': 31.7,
   'tempmin': 23.3,
   'temp': 27.2,
   'feelslikemax': 32.9,
   'feelslikemin': 23.3,
   'feelslike': 27.9,
   'dew': 18.9,
   'humidity': 61.9,
   'precip': 0.0,
   'precipprob': 0.0,
   'precipcover': 0.0,
   'preciptype': None,
   'snow': None,
   'snowdepth': None,
   'windgust': None,
   'windspeed': 16.7,
   'winddir': 298.5,
   'pressure': 1013.7,
   'cloudcover': 23.0,
   'visibility': 2.8,
   'solarradiation': None,
   'solarenergy': None,
   'uvindex': None,
   'sunrise': '07:12:28',
   'sunriseEpoch': 1641174148,
   'sunset': '18:13:47',
   'sunsetEpoch': 1641213827,
   'moonphase': 0.0,
   'conditions': 'Partially cloudy',
   'description': 'Partly cloudy throughout the day.',
   'icon': 'partly-cloudy-day',
   'stations': ['43058099999',
    'VABB',
    'VAJJ',
    '43003099999',
    '43057099999',
    '43060099999'],
   'source': 'obs'},
  {'datetime': '2022-01-04',
   'datetimeEpoch': 1641234600,
   'tempmax': 31.0,
   'tempmin': 23.3,
   'temp': 27.1,
   'feelslikemax': 32.8,
   'feelslikemin': 23.3,
   'feelslike': 27.9,
   'dew': 19.4,
   'humidity': 63.5,
   'precip': 0.0,
   'precipprob': 0.0,
   'precipcover': 0.0,
   'preciptype': None,
   'snow': None,
   'snowdepth': None,
   'windgust': None,
   'windspeed': 15.4,
   'winddir': 224.0,
   'pressure': 1013.7,
   'cloudcover': 0.6,
   'visibility': 2.6,
   'solarradiation': None,
   'solarenergy': None,
   'uvindex': None,
   'sunrise': '07:12:45',
   'sunriseEpoch': 1641260565,
   'sunset': '18:14:24',
   'sunsetEpoch': 1641300264,
   'moonphase': 0.05,
   'conditions': 'Clear',
   'description': 'Clear conditions throughout the day.',
   'icon': 'clear-day',
   'stations': ['43058099999',
    'VABB',
    'VAJJ',
    '43003099999',
    '43057099999',
    '43060099999'],
   'source': 'obs'},
  {'datetime': '2022-01-05',
   'datetimeEpoch': 1641321000,
   'tempmax': 30.4,
   'tempmin': 23.4,
   'temp': 26.5,
   'feelslikemax': 32.0,
   'feelslikemin': 23.4,
   'feelslike': 27.4,
   'dew': 21.0,
   'humidity': 72.9,
   'precip': 0.0,
   'precipprob': 0.0,
   'precipcover': 0.0,
   'preciptype': None,
   'snow': None,
   'snowdepth': None,
   'windgust': None,
   'windspeed': 14.9,
   'winddir': 281.7,
   'pressure': 1013.2,
   'cloudcover': 1.1,
   'visibility': 2.1,
   'solarradiation': None,
   'solarenergy': None,
   'uvindex': None,
   'sunrise': '07:13:02',
   'sunriseEpoch': 1641346982,
   'sunset': '18:15:02',
   'sunsetEpoch': 1641386702,
   'moonphase': 0.08,
   'conditions': 'Clear',
   'description': 'Clear conditions throughout the day.',
   'icon': 'clear-day',
   'stations': ['43058099999',
    'VABB',
    'VAJJ',
    '43003099999',
    '43057099999',
    '43060099999'],
   'source': 'obs'},
  {'datetime': '2022-01-06',
   'datetimeEpoch': 1641407400,
   'tempmax': 28.7,
   'tempmin': 23.2,
   'temp': 25.7,
   'feelslikemax': 30.1,
   'feelslikemin': 23.2,
   'feelslike': 26.2,
   'dew': 20.5,
   'humidity': 74.0,
   'precip': 0.0,
   'precipprob': 0.0,
   'precipcover': 0.0,
   'preciptype': None,
   'snow': None,
   'snowdepth': None,
   'windgust': None,
   'windspeed': 18.7,
   'winddir': 313.5,
   'pressure': 1012.8,
   'cloudcover': 11.2,
   'visibility': 2.5,
   'solarradiation': None,
   'solarenergy': None,
   'uvindex': None,
   'sunrise': '07:13:18',
   'sunriseEpoch': 1641433398,
   'sunset': '18:15:40',
   'sunsetEpoch': 1641473140,
   'moonphase': 0.11,
   'conditions': 'Clear',
   'description': 'Clear conditions throughout the day.',
   'icon': 'clear-day',
   'stations': ['43058099999',
    'VABB',
    'VAJJ',
    '43003099999',
    '43057099999',
    '43060099999'],
   'source': 'obs'},
  {'datetime': '2022-01-07',
   'datetimeEpoch': 1641493800,
   'tempmax': 28.8,
   'tempmin': 22.2,
   'temp': 25.6,
   'feelslikemax': 31.0,
   'feelslikemin': 22.2,
   'feelslike': 26.3,
   'dew': 20.6,
   'humidity': 74.8,
   'precip': 0.0,
   'precipprob': 0.0,
   'precipcover': 0.0,
   'preciptype': None,
   'snow': None,
   'snowdepth': None,
   'windgust': None,
   'windspeed': 18.7,
   'winddir': 205.3,
   'pressure': 1012.2,
   'cloudcover': 5.2,
   'visibility': 2.3,
   'solarradiation': None,
   'solarenergy': None,
   'uvindex': None,
   'sunrise': '07:13:32',
   'sunriseEpoch': 1641519812,
   'sunset': '18:16:18',
   'sunsetEpoch': 1641559578,
   'moonphase': 0.15,
   'conditions': 'Clear',
   'description': 'Clear conditions throughout the day.',
   'icon': 'clear-day',
   'stations': ['43058099999',
    'VABB',
    'VAJJ',
    '43003099999',
    '43057099999',
    '43060099999'],
   'source': 'obs'}],
 'stations': {'43058099999': {'distance': 34329.0,
   'latitude': 18.633,
   'longitude': 72.867,
   'useCount': 0,
   'id': '43058099999',
   'name': 'ALIBAG, IN',
   'quality': 53,
   'contribution': 0.0},
  '43003099999': {'distance': 16894.0,
   'latitude': 19.089,
   'longitude': 72.868,
   'useCount': 0,
   'id': '43003099999',
   'name': 'CHHATRAPATI SHIVAJI INTERNATIONAL, IN',
   'quality': 99,
   'contribution': 0.0},
  '43057099999': {'distance': 4864.0,
   'latitude': 18.9,
   'longitude': 72.817,
   'useCount': 0,
   'id': '43057099999',
   'name': 'BOMBAY COLABA, IN',
   'quality': 55,
   'contribution': 0.0},
  'VABB': {'distance': 20023.0,
   'latitude': 19.12,
   'longitude': 72.84,
   'useCount': 0,
   'id': 'VABB',
   'name': 'VABB',
   'quality': 50,
   'contribution': 0.0},
  'VAJJ': {'distance': 19081.0,
   'latitude': 19.11,
   'longitude': 72.81,
   'useCount': 0,
   'id': 'VAJJ',
   'name': 'VAJJ',
   'quality': 21,
   'contribution': 0.0},
  '43060099999': {'distance': 47461.0,
   'latitude': 18.983,
   'longitude': 73.283,
   'useCount': 0,
   'id': '43060099999',
   'name': 'MATHERAN, IN',
   'quality': 54,
   'contribution': 0.0}}}

In [184]:
import pandas as pd

# Extract weather data
weather_days = [
    {
        'Date': day['datetime'], 
        'Temp_Max': day['tempmax'], 
        'Temp_Min': day['tempmin'], 
        'Humidity': day['humidity']
    } 
    for day in weather_data['days']
]

# Convert to DataFrame
df_weather = pd.DataFrame(weather_days)

# Display the extracted weather data
print(df_weather)

         Date  Temp_Max  Temp_Min  Humidity
0  2022-01-01      31.4      22.7      59.0
1  2022-01-02      31.1      22.7      61.7
2  2022-01-03      31.7      23.3      61.9
3  2022-01-04      31.0      23.3      63.5
4  2022-01-05      30.4      23.4      72.9
5  2022-01-06      28.7      23.2      74.0
6  2022-01-07      28.8      22.2      74.8

In [160]:
# Ensure Year column is properly formatted as string for merging
df['Year'] = df['Year'].astype(str)

# Display crop yield data
print(df.head())

  Domain Code                        Domain  Area Code (M49)   Area  \
0         QCL  Crops and livestock products              356  India
1         QCL  Crops and livestock products              356  India
2         QCL  Crops and livestock products              356  India
3         QCL  Crops and livestock products              356  India
4         QCL  Crops and livestock products              356  India

   Element Code         Element Item Code (CPC)  \
0          5312  Area harvested           01654
1          5419           Yield           01654
2          5510      Production           01654
3          5312  Area harvested           01654
4          5419           Yield           01654

                                                Item  Year Code  Year  \
0  Anise, badian, coriander, cumin, caraway, fenn...       1961  1961
1  Anise, badian, coriander, cumin, caraway, fenn...       1961  1961
2  Anise, badian, coriander, cumin, caraway, fenn...       1961  1961
3  Anise, badian, coriander, cumin, caraway, fenn...       1962  1962
4  Anise, badian, coriander, cumin, caraway, fenn...       1962  1962

       Unit    Value Flag Flag Description Note
0        ha  90000.0    E  Estimated value  NaN
1  100 g/ha   5000.0    E  Estimated value  NaN
2         t  45000.0    E  Estimated value  NaN
3        ha  90000.0    E  Estimated value  NaN
4  100 g/ha   5000.0    E  Estimated value  NaN

In [191]:
# Filter for Maharashtra data (since no specific data for Mumbai)
maharashtra_data = df[df['State_Name'] == 'Maharashtra']

# Display filtered data
maharashtra_data.head()

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
125191,Maharashtra,AHMEDNAGAR,1997,Autumn,Maize,1.0,1113.0
125192,Maharashtra,AHMEDNAGAR,1997,Kharif,Arhar/Tur,17600.0,6300.0
125193,Maharashtra,AHMEDNAGAR,1997,Kharif,Bajra,274100.0,152800.0
125194,Maharashtra,AHMEDNAGAR,1997,Kharif,Gram,40800.0,18600.0
125195,Maharashtra,AHMEDNAGAR,1997,Kharif,Jowar,900.0,1100.0

In [189]:
# If you need to merge based on a specific date range, ensure the 'Date' columns match.
df_weather['Year'] = pd.to_datetime(df_weather['Date']).dt.year.astype(str)

df['Crop_Year'] = df['Crop_Year'].astype(str)

# Merge the two DataFrames on 'Year'
df_merged = pd.merge(df, df_weather, left_on='Crop_Year', right_on='Year', how='inner')


print(df_merged.head())

Empty DataFrame
Columns: [State_Name, District_Name, Crop_Year, Season, Crop, Area, Production, Date, Temp_Max, Temp_Min, Humidity, Year]
Index: []

In [ ]:
print("Unique Year values in Crop Yield Data (df):")
print(df['Year'].unique())

print("\nUnique Year values in Weather Data (df_weather):")
print(df_weather['Year'].unique())